server {
    listen 80;
    server_name _;

    # Serve shell static files
    location / {
        root   /usr/share/nginx/html;
        index  index.html;
        try_files $uri $uri/ /index.html;
    }

    # Health check endpoint — ALB uses this
    location /health {
        access_log off;
        return 200 'ok';
        add_header Content-Type text/plain;
    }
}
